### PR TITLE
expanded row styling

### PR DESCRIPTION
**Pull request by andreievg**

### CODE REVIEW

**Comment by andreievg** [comment]
@Chris-Petty can you explain how you would implement this `via usage`.

Can't dynamically update row style on expansion from react native generic table page (or from any other repos that uses it), unless the whole table is re-rendered. 
`I think it'd be tedious if we implemented a prop for the style of every different state`, yes, but have no time to rewrite react native data table so it re-renders on style change.

**Comment by Chris-Petty** [comment]
Ah I was hoping that props wouldn't rerender the whole thing. Something to keep in mind for rewrite then.

**Comment by Chris-Petty** [comment]
@andreievg if you bump the patch version I'll merge

**Comment by andreievg** [comment]
Cheers @Chris-Petty, bumped

**Pull request merged**
